version: '3.4'

services:
  web:
    image:  ${DOCKER_REGISTRY-}tododiligent
    build:
      context: ./ToDoDiligent
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "tvojjakpassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  frontend:
    build:
      context: ./frontendd
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
    networks:
      - frontend-net
      - backend-net

networks:
  frontend-net:
  backend-net:
