
version: '3.4'

services:
  web:
    image:  ${DOCKER_REGISTRY-}tododiligent
    build:
      context: .
      dockerfile: ToDoDiligent\Dockerfile
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "tvojjakpassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
